import ChairWarp.Gamma

/-!
# Integer poses as isometries of Euclidean 3-space

`E = EuclideanSpace ℝ (Fin 3)`. A rotation `r ∈ R24` acts linearly by `x ↦ (s i * x (p i))_i`;
a pose adds its integer translation. We prove these maps are isometries, that pose composition is
composition of maps, and build `GammaGeom`, the subgroup of `E ≃ᵢ E` generated by all poses in `Γ`.
Every tile of every substitution patch and every atlas contact is realised inside `GammaGeom`.
-/

open scoped BigOperators

abbrev E := EuclideanSpace ℝ (Fin 3)

namespace Rot

lemma bijective_p : ∀ r ∈ R24, Function.Bijective r.p := by decide +kernel

/-- Linear action on `E`. -/
noncomputable def lin (r : Rot) : E →ₗ[ℝ] E where
  toFun x := WithLp.toLp 2 fun i => (r.s i : ℝ) * x (r.p i)
  map_add' x y := by ext i; simp [mul_add]
  map_smul' c x := by ext i; simp; ring

@[simp] lemma lin_apply (r : Rot) (x : E) (i : Fin 3) : r.lin x i = (r.s i : ℝ) * x (r.p i) := rfl

lemma lin_comp (r q : Rot) (x : E) : (r.comp q).lin x = r.lin (q.lin x) := by
  ext i; simp [comp, mul_assoc]

lemma lin_id (x : E) : Rot.id.lin x = x := by
  ext i; fin_cases i <;> simp [Rot.id]

lemma norm_lin {r : Rot} (hr : r ∈ R24) (x : E) : ‖r.lin x‖ = ‖x‖ := by
  have hs := signs_unit r hr
  have hsq : ∀ i, ((r.s i : ℝ)) ^ 2 = 1 := by
    intro i; rcases hs i with h | h <;> simp [h]
  have key : ‖r.lin x‖ ^ 2 = ‖x‖ ^ 2 := by
    rw [EuclideanSpace.real_norm_sq_eq, EuclideanSpace.real_norm_sq_eq]
    simp only [lin_apply, mul_pow, hsq, one_mul]
    exact Equiv.sum_comp (Equiv.ofBijective _ (bijective_p r hr)) (fun i => x i ^ 2)
  rw [← Real.sqrt_sq (norm_nonneg (r.lin x)), key, Real.sqrt_sq (norm_nonneg x)]

/-- The inverse rotation, found in the finite list. -/
def inv (r : Rot) : Rot := (R24.find? fun q => r.comp q == Rot.id).getD Rot.id

lemma inv_spec : ∀ r ∈ R24, r.inv ∈ R24 ∧ r.comp r.inv = Rot.id ∧ r.inv.comp r = Rot.id := by
  decide +kernel

lemma lin_inv_cancel {r : Rot} (hr : r ∈ R24) (x : E) : r.lin (r.inv.lin x) = x := by
  rw [← lin_comp, (inv_spec r hr).2.1, lin_id]

lemma lin_cancel_inv {r : Rot} (hr : r ∈ R24) (x : E) : r.inv.lin (r.lin x) = x := by
  rw [← lin_comp, (inv_spec r hr).2.2, lin_id]

end Rot

/-- Integer vector as a point of `E`. -/
noncomputable def vec (t : V) : E := WithLp.toLp 2 fun i => (t i : ℝ)

@[simp] lemma vec_apply (t : V) (i : Fin 3) : vec t i = (t i : ℝ) := rfl

namespace Pose

/-- The map `x ↦ r x + t`. -/
noncomputable def toFun (P : Pose) (x : E) : E := P.r.lin x + vec P.t

lemma toFun_comp (P Q : Pose) (x : E) : (P.comp Q).toFun x = P.toFun (Q.toFun x) := by
  ext i
  simp [toFun, comp, Rot.lin_comp, Rot.act, map_add]
  ring

/-- A pose in `Γ` is an isometric equivalence of `E`. -/
noncomputable def toIso (P : Pose) (hP : P.InGamma) : E ≃ᵢ E where
  toFun := P.toFun
  invFun y := P.r.inv.lin (y - vec P.t)
  left_inv x := by simp [toFun, Rot.lin_cancel_inv hP.1]
  right_inv y := by simp [toFun, Rot.lin_inv_cancel hP.1]
  isometry_toFun := by
    refine Isometry.of_dist_eq fun x y => ?_
    rw [dist_eq_norm, dist_eq_norm, toFun, toFun, add_sub_add_right_eq_sub, ← map_sub,
      Rot.norm_lin hP.1]

@[simp] lemma toIso_apply (P : Pose) (hP : P.InGamma) (x : E) : P.toIso hP x = P.toFun x := rfl

end Pose

/-- The generators: isometries realised by poses of `Γ`. -/
noncomputable def gammaGens : Set (E ≃ᵢ E) := {γ | ∃ P : Pose, ∃ hP : P.InGamma, γ = P.toIso hP}

/-- Chair44's motion group as a subgroup of isometries of `E`. -/
noncomputable def GammaGeom : Subgroup (E ≃ᵢ E) := Subgroup.closure gammaGens

lemma toIso_mem (P : Pose) (hP : P.InGamma) : P.toIso hP ∈ GammaGeom :=
  Subgroup.subset_closure ⟨P, hP, rfl⟩

/-- Every tile of every substitution patch is placed by an element of `GammaGeom`. -/
theorem level_mem (n : ℕ) (P : Pose) (h : P ∈ level n) :
    P.toIso (level_inGamma n P h) ∈ GammaGeom := toIso_mem _ _

/-- Every contact of the 44-contact atlas is an element of `GammaGeom`. -/
theorem atlas_mem (c : Pose) (h : c ∈ atlas44) : c.toIso (atlas_inGamma c h) ∈ GammaGeom :=
  toIso_mem _ _

/-- Composition of poses is composition of isometries. -/
theorem toIso_comp (P Q : Pose) (hP : P.InGamma) (hQ : Q.InGamma) :
    (P.comp Q).toIso (Pose.comp_inGamma hP hQ) = P.toIso hP * Q.toIso hQ := by
  ext x : 1
  simp [Pose.toFun_comp]
